/* Workflow OS Shell Runtime v1.0 — artifacts/shared/shell.js
 * WP: WP-UI-005 | Stage: D | Generated by scripts/lib/ui-shell.js
 * Requires: artifacts/shared/shell.css
 * Contract: contracts/system-api/events.schema.json (CloudEvents 1.0)
 */
(function (root) {
  'use strict';

  root.WfShell = root.WfShell || {};
  var WfShell = root.WfShell;

  // ── Toast ───────────────────────────────────────────────────────────────────
  WfShell.toast = function (message, type) {
    type = type || 'pass';
    var container = document.querySelector('.wf-toast-container');
    if (!container) {
      container = document.createElement('div');
      container.className = 'wf-toast-container';
      document.body.appendChild(container);
    }
    var el = document.createElement('div');
    el.className = 'wf-toast wf-toast--' + type;
    el.textContent = message;
    container.appendChild(el);
    setTimeout(function () { el.remove(); }, 4000);
  };

  // ── SSE ─────────────────────────────────────────────────────────────────────
  var _src          = null;
  var _handlers     = {};   // { eventType: [fn, ...] }
  var _retryCount   = 0;
  var _retryDelay   = 1000; // ms, doubles on each failure (max 30 s)
  var _connected    = false;
  var _connectUrl   = '/api/v1/system/events';
  var _SSE_TYPES    = [
    'system.health.updated',
    'system.flag.toggled',
    'system.rollback.triggered',
    'system.quality-gate.updated',
    'system.domain.lifecycle-changed',
  ];
  var MAX_RETRIES   = 10;
  var MAX_DELAY_MS  = 30000;

  function _setIndicator(state) {
    _connected = (state === 'online');
    document.querySelectorAll('[data-sse-indicator]').forEach(function (el) {
      el.className = 'wf-sse-indicator wf-sse-indicator--' + state;
      var labels = { online: 'System OS 연결됨', offline: 'System OS 연결 끊김', connecting: 'System OS 재연결 중...' };
      el.title = labels[state] || state;
      el.setAttribute('aria-label', el.title);
    });
  }

  function _dispatch(data) {
    var type = data.type || (data.data && data.data.type);
    [type, '*'].forEach(function (t) {
      if (t && _handlers[t]) {
        _handlers[t].forEach(function (fn) {
          try { fn(data); } catch (e) { console.error('[WfShell SSE handler error]', t, e); }
        });
      }
    });
  }

  WfShell.sse = {
    /** @param {string} [url]  Defaults to /api/v1/system/events */
    connect: function (url) {
      _connectUrl = url || _connectUrl;
      if (_src) { _src.close(); _src = null; }
      _setIndicator('connecting');

      if (!root.EventSource) {
        console.warn('[WfShell] EventSource not supported');
        _setIndicator('offline');
        return;
      }

      try { _src = new EventSource(_connectUrl); }
      catch (e) { _setIndicator('offline'); return; }

      _src.onopen = function () {
        _retryCount  = 0;
        _retryDelay  = 1000;
        _setIndicator('online');
      };

      _src.onerror = function () {
        _setIndicator('offline');
        _src.close(); _src = null;
        if (_retryCount < MAX_RETRIES) {
          _retryCount++;
          _retryDelay = Math.min(_retryDelay * 2, MAX_DELAY_MS);
          WfShell.toast('재연결 중... (' + _retryCount + '/' + MAX_RETRIES + ')', 'warn');
          setTimeout(function () { WfShell.sse.connect(); }, _retryDelay);
        } else {
          WfShell.toast('실시간 연결 실패 — 페이지를 새로고침하세요', 'fail');
        }
      };

      // Generic onmessage (data: JSON without event: field)
      _src.onmessage = function (e) {
        try { _dispatch(JSON.parse(e.data)); } catch (_) {}
      };

      // Named CloudEvents listeners
      _SSE_TYPES.forEach(function (evtType) {
        _src.addEventListener(evtType, function (e) {
          try { _dispatch(JSON.parse(e.data)); } catch (_) {}
        });
      });
    },

    /** Register a handler for a specific SSE event type (or '*' for all). */
    on: function (eventType, handler) {
      if (!_handlers[eventType]) _handlers[eventType] = [];
      _handlers[eventType].push(handler);
    },

    off: function (eventType, handler) {
      if (!_handlers[eventType]) return;
      _handlers[eventType] = _handlers[eventType].filter(function (fn) { return fn !== handler; });
    },

    disconnect: function () {
      if (_src) { _src.close(); _src = null; }
      _setIndicator('offline');
    },

    isConnected: function () { return _connected; },
  };

  // ── Permissions ──────────────────────────────────────────────────────────────
  WfShell.permissions = {
    _role: null,

    /** Call after loading the page with the current user's role. */
    setRole: function (role) {
      this._role = role;
      this._applyToDOM();
    },

    can: function (permission) {
      if (this._role === 'system.admin') return true;
      if (permission === 'system.viewer' || permission === 'domain.viewer') {
        return ['system.viewer', 'domain.viewer', 'system.admin'].includes(this._role);
      }
      return false;
    },

    _applyToDOM: function () {
      var self = this;
      document.querySelectorAll('[data-require-permission]').forEach(function (el) {
        el.hidden = !self.can(el.getAttribute('data-require-permission'));
      });
      document.querySelectorAll('[data-disable-without-permission]').forEach(function (el) {
        var perm = el.getAttribute('data-disable-without-permission');
        if (!self.can(perm)) {
          el.disabled = true;
          el.setAttribute('aria-disabled', 'true');
          el.title = '이 작업에는 ' + perm + ' 권한이 필요합니다';
        }
      });
    },
  };

  // ── Built-in SSE → DOM handlers ──────────────────────────────────────────────

  // system.health.updated → update health gauge + score for matching domain cards
  WfShell.sse.on('system.health.updated', function (payload) {
    var d     = payload.data || {};
    var domId = d.domain_id;
    var score = d.score;
    if (!domId || score === undefined) return;

    document.querySelectorAll('[data-domain-id="' + domId + '"]').forEach(function (card) {
      var fill  = card.querySelector('.wf-gauge__fill');
      var label = card.querySelector('[data-health-score]');
      if (fill)  fill.style.width = score + '%';
      if (label) label.textContent = score;

      // Update fill class based on score
      if (fill) {
        fill.classList.toggle('wf-gauge__fill--warn', score < 70 && score >= 50);
        fill.classList.toggle('wf-gauge__fill--fail', score < 50);
      }
    });
  });

  // system.flag.toggled → update toggle switch in flag panel
  WfShell.sse.on('system.flag.toggled', function (payload) {
    var d = payload.data || {};
    if (!d.flag_id) return;

    document.querySelectorAll('[data-flag-id="' + d.flag_id + '"]').forEach(function (el) {
      var input = el.querySelector('input[type=checkbox]') || el;
      if (input && input.type === 'checkbox') {
        input.checked = Boolean(d.enabled);
      }
      // Update dot indicators
      el.querySelectorAll('[data-flag-dot]').forEach(function (dot) {
        dot.style.color = d.enabled
          ? 'var(--wf-color-pass)'
          : 'var(--wf-color-neutral)';
      });
    });
    WfShell.toast((d.enabled ? '활성화' : '비활성화') + ': ' + d.flag_id, 'pass');
  });

  // system.rollback.triggered → show toast
  WfShell.sse.on('system.rollback.triggered', function (payload) {
    var d = payload.data || {};
    WfShell.toast('롤백 시작: ' + (d.domain || '알 수 없음'), 'warn');
  });

  // system.quality-gate.updated → append to quality timeline if present
  WfShell.sse.on('system.quality-gate.updated', function (payload) {
    var d = payload.data || {};
    var timeline = document.querySelector('[data-quality-timeline]');
    if (!timeline) return;

    var row = document.createElement('div');
    row.className = 'wf-timeline-row';
    row.innerHTML =
      '<span class="wf-timeline-row__time">방금</span>' +
      '<span class="wf-timeline-row__domain">' + (d.domain || 'system') + '</span>' +
      '<span class="wf-timeline-row__action">' + (d.gate_id || '') + '</span>' +
      '<span class="wf-badge wf-badge--' + (d.result === 'PASS' ? 'pass' : 'fail') + '">' + (d.result || '') + '</span>';
    timeline.prepend(row);
  });

  // ── Confirmation modal helper ────────────────────────────────────────────────
  /**
   * Show a confirmation modal with a required text input.
   * Resolves true if confirmed, false if cancelled.
   *
   * @param {{ title: string, body: string, confirmText: string, dangerLabel?: string }} opts
   * @returns {Promise<boolean>}
   */
  WfShell.confirm = function (opts) {
    return new Promise(function (resolve) {
      var overlay = document.createElement('div');
      overlay.className = 'wf-modal-overlay';
      overlay.innerHTML =
        '<div class="wf-modal" role="dialog" aria-modal="true">' +
        '  <div class="wf-modal__title">' + _esc(opts.title) + '</div>' +
        '  <div class="wf-modal__body">' + _esc(opts.body) + '</div>' +
        '  <input type="text" class="wf-modal__confirm-input" placeholder="' + _esc(opts.confirmText) + '" autocomplete="off" style="width:100%;margin-bottom:.75rem;padding:.4rem .6rem;background:var(--wf-color-bg);border:1px solid var(--wf-color-border);color:var(--wf-color-text);border-radius:var(--wf-radius);font-size:.875rem;">' +
        '  <div class="wf-modal__actions">' +
        '    <button class="wf-btn wf-btn--ghost wf-modal__cancel">취소</button>' +
        '    <button class="wf-btn wf-btn--danger wf-modal__execute" disabled>' + _esc(opts.dangerLabel || '실행') + '</button>' +
        '  </div>' +
        '</div>';
      document.body.appendChild(overlay);

      var input   = overlay.querySelector('.wf-modal__confirm-input');
      var execBtn = overlay.querySelector('.wf-modal__execute');
      var cancelBtn = overlay.querySelector('.wf-modal__cancel');

      input.addEventListener('input', function () {
        execBtn.disabled = input.value !== opts.confirmText;
      });
      execBtn.addEventListener('click', function () {
        overlay.remove(); resolve(true);
      });
      cancelBtn.addEventListener('click', function () {
        overlay.remove(); resolve(false);
      });
      overlay.addEventListener('keydown', function (e) {
        if (e.key === 'Escape') { overlay.remove(); resolve(false); }
      });
      input.focus();
    });
  };

  function _esc(s) {
    return String(s || '')
      .replace(/&/g,'&amp;').replace(/</g,'&lt;')
      .replace(/>/g,'&gt;').replace(/"/g,'&quot;');
  }

  // ── Auto-connect ──────────────────────────────────────────────────────────────
  document.addEventListener('DOMContentLoaded', function () {
    var trigger = document.querySelector('[data-sse-connect]');
    if (trigger) {
      WfShell.sse.connect(trigger.getAttribute('data-sse-connect') || undefined);
    }
  });

}(typeof globalThis !== 'undefined' ? globalThis : window));