'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { execFile } = require('node:child_process');
const { promisify } = require('node:util');
const { test } = require('node:test');
const assert = require('node:assert/strict');

const execFileAsync = promisify(execFile);

test('[master planner] bundles per-screen UI guides for operators and planners', async () => {
  const repoRoot = path.resolve(__dirname, '../../..');
  const artifactPath = path.join(repoRoot, 'artifacts', 'master-planner', 'index.html');

  const { stderr } = await execFileAsync('python3', ['scripts/generate-master-planner.py', '--silent'], {
    cwd: repoRoot,
  });

  assert.equal(stderr, '');

  const html = fs.readFileSync(artifactPath, 'utf8');
  assert.match(html, /"ui_guides"/);
  assert.match(html, /"adapter_catalog"/);
  assert.match(html, /"adapter_scorecards"/);
  assert.match(html, /"planning_studio_modes"/);
  assert.match(html, /"adapter_transition_playbooks"/);
  assert.match(html, /"execution_packet_templates"/);
  assert.match(html, /"context_routing_profiles"/);
  assert.match(html, /"learning_replay_lenses"/);
  assert.match(html, /"project_blueprints"/);
  assert.match(html, /"project_intake_canvas"/);
  assert.match(html, /"adapter_compatibility"/);
  assert.match(html, /"ai_learning_tracks"/);
  assert.match(html, /"learning_mastery_map"/);
  assert.match(html, /"ai_runtime_recipes"/);
  assert.match(html, /"master_os_relations"/);
  assert.match(html, /"benchmark_intelligence"/);
  assert.match(html, /화면 설명서/);
  assert.match(html, /어댑터 레지스트리/);
  assert.match(html, /어댑터 Scorecard/);
  assert.match(html, /국내외 벤치마크 기반 개선 포커스/);
  assert.match(html, /필수 개선 3종/);
  assert.match(html, /Benchmark Review Baseline/);
  assert.match(html, /마스터 UI 기획 진실면 강화/);
  assert.match(html, /최소 문맥 라우팅 성능 강화/);
  assert.match(html, /학습형 Live Ops 콕핏 강화/);
  assert.match(html, /국내외 벤치마크 신호/);
  assert.match(html, /프로젝트 시작 블루프린트/);
  assert.match(html, /프로젝트 시작 질문지/);
  assert.match(html, /코어와 확장 경계를 어떻게 가져갈 것인가/);
  assert.match(html, /어떤 학습 surface가 가장 중요한가/);
  assert.match(html, /문맥 예산은 얼마나 엄격하게 관리할 것인가/);
  assert.match(html, /추천 조합/);
  assert.match(html, /Launch Brief 복사/);
  assert.match(html, /Planning Studio/);
  assert.match(html, /Planning Studio 복사/);
  assert.match(html, /Planning Variant Comparator/);
  assert.match(html, /Planning Patch Preview/);
  assert.match(html, /Snapshot Timeline/);
  assert.match(html, /Context Packet/);
  assert.match(html, /Context Packet 복사/);
  assert.match(html, /Context Bundle Export/);
  assert.match(html, /Context Lock Snapshot/);
  assert.match(html, /context-lock/);
  assert.match(html, /Context Drift Guard/);
  assert.match(html, /context-drift/);
  assert.match(html, /Re-read Queue/);
  assert.match(html, /reread-queue/);
  assert.match(html, /Context Routing Profile/);
  assert.match(html, /Context Exception Ledger/);
  assert.match(html, /context-exception/);
  assert.match(html, /Exception Packet Draft/);
  assert.match(html, /exception-packet/);
  assert.match(html, /Exception Replay Lens/);
  assert.match(html, /exception-replay/);
  assert.match(html, /Token Budget Meter/);
  assert.match(html, /Execution Packet Draft/);
  assert.match(html, /Execution Packet 복사/);
  assert.match(html, /Constraint Fit Checker/);
  assert.match(html, /check-fit/);
  assert.match(html, /Apply Handoff Kit/);
  assert.match(html, /Core Impact Boundary Map/);
  assert.match(html, /Handoff Bundle Composer/);
  assert.match(html, /handoff-bundle/);
  assert.match(html, /Verified Promote Pipeline/);
  assert.match(html, /wp:promote/);
  assert.match(html, /Promotion Pipeline Orchestrator/);
  assert.match(html, /promote-pipeline/);
  assert.match(html, /Readiness Brief/);
  assert.match(html, /readiness-brief/);
  assert.match(html, /Promotion Decision Deck/);
  assert.match(html, /promotion-decision/);
  assert.match(html, /Decision Apply Bridge/);
  assert.match(html, /decision-apply/);
  assert.match(html, /Apply Checkpoint Export/);
  assert.match(html, /apply-checkpoint/);
  assert.match(html, /Apply Timeline/);
  assert.match(html, /apply-timeline/);
  assert.match(html, /Packet Hierarchy Lens/);
  assert.match(html, /packet-hierarchy/);
  assert.match(html, /Capability Brief/);
  assert.match(html, /capability-brief/);
  assert.match(html, /Capability Planning Seed/);
  assert.match(html, /capability-seed/);
  assert.match(html, /Capability Seed Tuning Patch/);
  assert.match(html, /capability-seed-tuning/);
  assert.match(html, /Exception Routing Patch/);
  assert.match(html, /exception-routing/);
  assert.match(html, /Apply Outcome Scorecard/);
  assert.match(html, /apply-scorecard/);
  assert.match(html, /Blueprint Launch Deck/);
  assert.match(html, /blueprint-launch/);
  assert.match(html, /Learned Preset Memory/);
  assert.match(html, /learned-preset-memory/);
  assert.match(html, /Token ROI Report/);
  assert.match(html, /token-roi/);
  assert.match(html, /Proven Kickoff Deck/);
  assert.match(html, /proven-kickoff/);
  assert.match(html, /Adaptive Starter Preset/);
  assert.match(html, /adaptive-starter/);
  assert.match(html, /Token ROI Routing Patch/);
  assert.match(html, /token-roi-routing/);
  assert.match(html, /Kickoff Evidence Bundle/);
  assert.match(html, /kickoff-evidence/);
  assert.match(html, /Launch Brief Autopilot/);
  assert.match(html, /launch-brief-autopilot/);
  assert.match(html, /Routing Learning Ledger/);
  assert.match(html, /routing-learning/);
  assert.match(html, /Kickoff Ready Gate/);
  assert.match(html, /kickoff-ready-gate/);
  assert.match(html, /Benchmark Action Pack/);
  assert.match(html, /benchmark-pack/);
  assert.match(html, /Starter Preset Pack/);
  assert.match(html, /starter-preset/);
  assert.match(html, /Planning Studio에 적용/);
  assert.match(html, /Preset Apply Snapshot Link/);
  assert.match(html, /Starter Deliverables/);
  assert.match(html, /Starter Focus Cycle/);
  assert.match(html, /왜 이 조합인가/);
  assert.match(html, /추천 조합 기준 학습 여정/);
  assert.match(html, /AI 학습 플로우/);
  assert.match(html, /Adapter Transition Switchboard/);
  assert.match(html, /어댑터 호환성 매트릭스/);
  assert.match(html, /학습 숙련도 로드맵/);
  assert.match(html, /AI Runtime Recipes/);
  assert.match(html, /마스터 OS 관계 맵/);
  assert.match(html, /현재 목표 기준 추천 어댑터 우선순위/);
  assert.match(html, /핵심 KPI, 미결 인보이스, 예외 현황/);
  assert.match(html, /비동기 트랜스코딩 작업의 진행률과 실패 원인/);
  assert.match(html, /마스터 OS AI 스튜디오/);
  assert.match(html, /마스터 OS 기초/);
  assert.match(html, /Workflow OS 기본 구조 이해/);
  assert.match(html, /Planner-First Hybrid/);
  assert.match(html, /Live Ops Feed/);
  assert.match(html, /Alert Cockpit/);
  assert.match(html, /Study Replay/);
  assert.match(html, /Replay Next Packet/);
  assert.match(html, /replay-packet/);
  assert.match(html, /Structured Log Guardrail/);
  assert.match(html, /Auto refresh 15s/);
  assert.match(html, /Figma FigJam/);
  assert.match(html, /NAVER CLOVA/);
  assert.match(html, /OpenAI File Search/);
  assert.match(html, /OpenAI AgentKit/);
  assert.match(html, /Linear Cycles/);
  assert.match(html, /FigJam Project Status Template/);
  assert.match(html, /Figma Version History/);
  assert.match(html, /HyperCLOVA X/);
  assert.match(html, /GitHub Issue Fields/);
  assert.match(html, /GitHub Project Templates/);
  assert.match(html, /GitHub Projects/);
  assert.match(html, /GitHub Issues/);
  assert.match(html, /Jira Product Discovery/);
  assert.match(html, /Jira Product Discovery Features/);
  assert.match(html, /Linear의 curated focus 방식처럼/);
});
