'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { execFile } = require('node:child_process');
const { promisify } = require('node:util');
const { test } = require('node:test');
const assert = require('node:assert/strict');

const execFileAsync = promisify(execFile);

test('[mindmap control center interaction smoke] worker selection is wired to immediate dispatch controls', async () => {
  const repoRoot = path.resolve(__dirname, '../../..');
  const artifactPath = path.join(repoRoot, 'artifacts', 'mindmap', 'index.html');

  const { stderr } = await execFileAsync('node', ['scripts/generate-mindmap.js'], {
    cwd: repoRoot,
  });

  assert.equal(stderr, '');

  const html = fs.readFileSync(artifactPath, 'utf8');

  assert.match(html, /즉시 제어 worker/);
  assert.match(html, /롤백 대상/);
  assert.match(html, /id="execution-rollback-target"/);
  assert.match(html, /선택 domain 롤백/);
  assert.match(html, /즉시 가능 제어/);
  assert.match(html, /Stage 실행/);
  assert.match(html, /id="execution-stage-select"/);
  assert.match(html, /id="execution-stage-module"/);
  assert.match(html, /Stage dry-run/);
  assert.match(html, /Stage execute/);
  assert.match(html, /마지막 stage 재실행/);
  assert.match(html, /id="execution-worker-select"/);
  assert.match(html, /onchange="syncExecutionInputs\(\)"/);
  assert.match(html, /var workerEl = document\.getElementById\('execution-worker-select'\);/);
  assert.match(html, /var rollbackEl = document\.getElementById\('execution-rollback-target'\);/);
  assert.match(html, /function syncStageRunInputs\(\)/);
  assert.match(html, /function runSelectedStage\(executeMode\)/);
  assert.match(html, /function retryLastStageRun\(\)/);
  assert.match(html, /function applyStageRunHistory\(reports\)/);
  assert.match(html, /function setStageRunHistoryFilter\(filter\)/);
  assert.match(html, /function setStageRunSignalHistoryView\(mode\)/);
  assert.match(html, /function setStageRunSignalGroupCollapsed\(collapsed\)/);
  assert.match(html, /function setStageRunHistorySort\(sortMode\)/);
  assert.match(html, /function firstStageRunFailureEntry\(entries\)/);
  assert.match(html, /function stageRunFailureLocation\(report\)/);
  assert.match(html, /function stageRunFailureReason\(report\)/);
  assert.match(html, /function stageRunCurrentState\(report\)/);
  assert.match(html, /function stageRunRetryableSummary\(report\)/);
  assert.match(html, /function stageRunEvidenceStatus\(report\)/);
  assert.match(html, /function stageRunEvidenceError\(report\)/);
  assert.match(html, /function stageRunReleaseEvidenceStatus\(report\)/);
  assert.match(html, /function stageRunReleaseEvidenceError\(report\)/);
  assert.match(html, /function stageRunReleaseEvidencePath\(report\)/);
  assert.match(html, /function stageRunReleaseEvidenceCommand\(report\)/);
  assert.match(html, /function executionOperatorCockpitReleaseEvidenceSummary\(\)/);
  assert.match(html, /function executionOperatorCockpitReleaseEvidenceBlocker\(\)/);
  assert.match(html, /function executionOperatorCockpitReleaseEvidenceContractSummary\(\)/);
  assert.match(html, /function executionOperatorCockpitReleaseEvidenceNextAction\(\)/);
  assert.match(html, /function normalizeStageRunContract\(contract\)/);
  assert.match(html, /function normalizeStageRunQualityGate\(qualityGate\)/);
  assert.match(html, /function stageRunContractStatus\(\)/);
  assert.match(html, /function stageRunContractIssues\(\)/);
  assert.match(html, /function stageRunContractNextAction\(\)/);
  assert.match(html, /function stageRunQualityGateStatus\(\)/);
  assert.match(html, /function stageRunQualityGateSource\(\)/);
  assert.match(html, /function stageRunQualityGateReadiness\(\)/);
  assert.match(html, /function stageRunQualityGateNextAction\(\)/);
  assert.match(html, /function stageRunContractRecoveryPrompt\(\)/);
  assert.match(html, /function loadStageRunContractRecoveryPrompt\(\)/);
  assert.match(html, /function sendStageRunContractRecoveryPrompt\(\)/);
  assert.match(html, /function refreshStageRunContract\(\)/);
  assert.match(html, /function applyStageRunContract\(contract\)/);
  assert.match(html, /function applyStageRunQualityGate\(qualityGate\)/);
  assert.match(html, /function stageRunRequestId\(report\)/);
  assert.match(html, /function stageRunCorrelationId\(report\)/);
  assert.match(html, /function stageRunTraceQuery\(report\)/);
  assert.match(html, /function copyStageRunTraceQuery\(historyIndex\)/);
  assert.match(html, /function loadStageRunTracePrompt\(historyIndex\)/);
  assert.match(html, /function sendStageRunTracePrompt\(historyIndex\)/);
  assert.match(html, /function stageRunFailureBadgeMarkup\(report, historyIndex\)/);
  assert.match(html, /function stageRunFailureBadgeMarkupWithHandler\(report, historyIndex, handlerName\)/);
  assert.match(html, /function executionWorkerIndexValue\(worker, fallbackIndex\)/);
  assert.match(html, /function executionWorkerLabel\(worker, fallbackIndex\)/);
  assert.match(html, /function executionMatchesWorker\(activityWorkerName, worker, fallbackIndex\)/);
  assert.match(html, /function executionActivityWorkerLabel\(activity\)/);
  assert.match(html, /function executionSummaryWithIndexedWorker\(summary, activity\)/);
  assert.match(html, /function executionFailureLocationSummary\(summary, activity\)/);
  assert.match(html, /function executionFailureReasonSummary\(summary, activity\)/);
  assert.match(html, /function refreshExecutionSelectionUi\(\)/);
  assert.match(html, /function selectedExecutionWorkerLabel\(\)/);
  assert.match(html, /function rollbackModalSummary\(domainNode\)/);
  assert.match(html, /function rollbackModalContextEntries\(domainNode\)/);
  assert.match(html, /function rollbackModalMarkup\(domainNode\)/);
  assert.match(html, /function rollbackModalValidationState\(\)/);
  assert.match(html, /function refreshRollbackModalContext\(\)/);
  assert.match(html, /function refreshRollbackModalValidation\(\)/);
  assert.match(html, /function executionNextActionBase\(\)/);
  assert.match(html, /function executionNextAction\(\)/);
  assert.match(html, /function focusStageRunFailureSignal\(signalType, historyIndex\)/);
  assert.match(html, /function focusPinnedStageRunFailureSignal\(signalType, historyIndex\)/);
  assert.match(html, /function stepStageRunFailureMatch\(direction\)/);
  assert.match(html, /function stageRunMatchedCountLabel\(\)/);
  assert.match(html, /function stageRunSecondaryMatchCountLabel\(\)/);
  assert.match(html, /function stageRunQualityGateTone\(report\)/);
  assert.match(html, /function stageRunFocusedSignalLabel\(\)/);
  assert.match(html, /function pinStageRunFocusedEntry\(entries\)/);
  assert.match(html, /function setStageRunHistoryHighlight\(historyIndex\)/);
  assert.match(html, /function reuseStageRunHistory\(index\)/);
  assert.match(html, /function rerunStageHistory\(index, executeMode\)/);
  assert.match(html, /snapshot\.stage_run_last_report/);
  assert.match(html, /snapshot\.stage_run_recent_reports/);
  assert.match(html, /applyStageRunReport\(snapshot\.stage_run_last_report\)/);
  assert.match(html, /applyStageRunHistory\(snapshot\.stage_run_recent_reports\)/);
  assert.match(html, /applyStageRunContract\(snapshot\.stage_run_contract\)/);
  assert.match(html, /applyStageRunQualityGate\(snapshot\.stage_run_quality_gate\)/);
  assert.match(html, /applyStageRunHistory\(RAW\.meta\.stageRunHistory\)/);
  assert.match(html, /RAW\.meta\.stageRunLatest/);
  assert.match(html, /최근 이력/);
  assert.match(html, /전체 보기/);
  assert.match(html, /실패\/차단만/);
  assert.match(html, /execute만/);
  assert.match(html, /실패 우선 정렬/);
  assert.match(html, /최신순 정렬/);
  assert.match(html, /최근 실패 우선/);
  assert.match(html, /실패 명령:/);
  assert.match(html, /선행 조건:/);
  assert.match(html, /같은 신호 탐색/);
  assert.match(html, /매칭 /);
  assert.match(html, /현재 포커스/);
  assert.match(html, /같은 신호/);
  assert.match(html, /탐색 기준/);
  assert.match(html, /현재 포커스 이력/);
  assert.match(html, /현재 포커스 배치/);
  assert.match(html, /상단 고정/);
  assert.match(html, /보조 이력/);
  assert.match(html, /현재 포커스 카드/);
  assert.match(html, /같은 신호 그룹에서 현재 포커스 이력을 최상단에 고정했습니다\./);
  assert.match(html, /gate /);
  assert.match(html, /stageRunFailureBadgeMarkupWithHandler\(highlightedHistoryReport, highlightedHistoryEntry\.index, 'focusPinnedStageRunFailureSignal'\)/);
  assert.match(html, /현재 포커스 dry-run/);
  assert.match(html, /현재 포커스 execute/);
  assert.match(html, /같은 신호만 보기/);
  assert.match(html, /전체 이력 복원/);
  assert.match(html, /같은 신호 접기/);
  assert.match(html, /같은 신호 펼치기/);
  assert.match(html, /이전 매칭/);
  assert.match(html, /다음 매칭/);
  assert.match(html, /focusStageRunFailureSignal\('failed_command'/);
  assert.match(html, /focusStageRunFailureSignal\('prerequisites'/);
  assert.match(html, /focusPinnedStageRunFailureSignal\('failed_command'/);
  assert.match(html, /focusPinnedStageRunFailureSignal\('prerequisites'/);
  assert.match(html, /현재 상태/);
  assert.match(html, /실패 위치/);
  assert.match(html, /실패 원인/);
  assert.match(html, /운영 증거/);
  assert.match(html, /저장 오류/);
  assert.match(html, /Release Evidence/);
  assert.match(html, /Release Blocker/);
  assert.match(html, /Release 계약/);
  assert.match(html, /Release 다음 행동/);
  assert.match(html, /Release 명령 복사/);
  assert.match(html, /Release 명령 채우기/);
  assert.match(html, /Evidence 오류/);
  assert.match(html, /Evidence 경로/);
  assert.match(html, /Evidence 명령/);
  assert.match(html, /Quality Gate 판정/);
  assert.match(html, /Gate 판정 출처/);
  assert.match(html, /Gate 운영 준비/);
  assert.match(html, /Gate 다음 행동/);
  assert.match(html, /계약 드리프트/);
  assert.match(html, /드리프트 이슈/);
  assert.match(html, /계약 다음 행동/);
  assert.match(html, /계약 재확인/);
  assert.match(html, /복구 안내 채우기/);
  assert.match(html, /복구 안내 전송/);
  assert.match(html, /요청 ID/);
  assert.match(html, /상관 ID/);
  assert.match(html, /로그 확인/);
  assert.match(html, /즉시 전송 가드/);
  assert.match(html, /가능한 다음 행동/);
  assert.match(html, /재실행/);
  assert.match(html, /첫 실패 불러오기/);
  assert.match(html, /실행 패널에 채우기/);
  assert.match(html, /즉시 전송/);
  assert.match(html, /로그 추적 복사/);
  assert.match(html, /첫 실패 dry-run/);
  assert.match(html, /첫 실패 execute/);
  assert.match(html, /표시 개수/);
  assert.match(html, /이 기록 불러오기/);
  assert.match(html, /dry-run 재실행/);
  assert.match(html, /execute 재실행/);
  assert.match(html, /execution-history-item/);
  assert.match(html, /execution-history-item-' \+ entry\.index \+ '/);
  assert.match(html, /is-highlighted/);
  assert.match(html, /execution-history-pill/);
  assert.match(html, /execution-history-pill is-info/);
  assert.match(html, /execution-history-pill is-focus/);
  assert.match(html, /execution-history-anchor/);
  assert.match(html, /execution-failure-badges/);
  assert.match(html, /execution-failure-focus/);
  assert.match(html, /operator_guidance/);
  assert.match(html, /runtime_observability/);
  assert.match(html, /확인 필요 \/ 저장 관측 정보 없음/);
  assert.match(html, /저장 완료 \/ 운영 증거 기록됨/);
  assert.match(html, /저장 실패 \/ 응답은 수신됐지만 기록 저장이 실패했습니다\./);
  assert.match(html, /확인 필요 \/ release evidence 관측 정보 없음/);
  assert.match(html, /생성 완료 \/ release evidence 기록됨/);
  assert.match(html, /생성 실패 \/ 응답은 수신됐지만 release evidence 생성이 실패했습니다\./);
  assert.match(html, /확인 필요 \/ stage-run 계약 정보 없음/);
  assert.match(html, /정상 \/ latest-history-head와 release evidence 표면이 정렬됨/);
  assert.match(html, /드리프트 감지 \/ snapshot과 저장 정본 사이 확인 필요/);
  assert.match(html, /stage_run_contract 없음/);
  assert.match(html, /snapshot을 다시 불러와 stage-run 계약 상태를 확인하세요\./);
  assert.match(html, /현재 snapshot 계약이 정렬되어 있어 다음 Stage 또는 운영 반영으로 이동할 수 있습니다\./);
  assert.match(html, /stage-run을 다시 저장하거나 release evidence가 포함된 최신 실행 결과로 갱신하세요\./);
  assert.match(html, /stage-run 계약 드리프트 원인을 확인한 뒤 snapshot 정본을 다시 생성하세요\./);
  assert.match(html, /\[stage-run 계약 복구\]/);
  assert.match(html, /showToast\('채울 stage-run 계약 복구 안내가 없습니다\.'\);/);
  assert.match(html, /showToast\('stage-run 계약 복구 안내 반영 완료'\);/);
  assert.match(html, /showToast\('stage-run 계약 재확인 완료'\);/);
  assert.match(html, /showToast\('stage-run 계약 재확인 실패'\);/);
  assert.match(html, /release_evidence 없음/);
  assert.match(html, /release evidence 오류 기록 없음/);
  assert.match(html, /release evidence blocker 정보 없음/);
  assert.match(html, /stage-run contract 정보 없음/);
  assert.match(html, /확인 필요 \/ stage-run quality gate 정보 없음/);
  assert.match(html, /대기 \/ dry-run-only 상태로 실제 quality gate가 아직 실행되지 않았습니다\./);
  assert.match(html, /정상 \/ quality gate PASS가 확보되었습니다\./);
  assert.match(html, /확인 필요 \/ quality gate 결과를 아직 확정할 수 없습니다\./);
  assert.match(html, /불가 \/ release evidence 준비 판정을 내릴 수 없습니다\./);
  assert.match(html, /대기 \/ release evidence 준비 판정에 아직 사용할 수 없습니다\./);
  assert.match(html, /가능 \/ release evidence 준비 판정에 사용할 수 있습니다\./);
  assert.match(html, /stage_run_quality_gate 없음/);
  assert.match(html, /snapshot을 다시 불러와 quality gate 판정 상태를 확인하세요\./);
  assert.match(html, /'reported=' \+ reported/);
  assert.match(html, /'mode=' \+ qualityGate\.execution_mode/);
  assert.match(html, /qualityGate\.next_action/);
  assert.match(html, /qualityGate\.blocker/);
  assert.match(html, /qualityGate\.ready_for_release_evidence === true/);
  assert.match(html, /release evidence를 확인하고 다음 Stage 또는 운영 반영으로 이동하세요\./);
  assert.match(html, /release evidence artifact를 다시 생성해 상태를 확인하세요\./);
  assert.match(html, /Stage 품질 게이트 결과를 다시 확보한 뒤 release evidence를 재생성하세요\./);
  assert.match(html, /stage-run 계약 드리프트를 먼저 해소한 뒤 release evidence를 다시 생성하세요\./);
  assert.match(html, /현재 blocker를 해소한 뒤 release evidence를 다시 생성하세요\./);
  assert.match(html, /release evidence 생성 실패 원인을 확인한 뒤 execute 재실행 또는 증거 생성 명령을 다시 실행하세요\./);
  assert.match(html, /toast: 'release evidence 생성 명령을 준비했습니다\.',/);
  assert.match(html, /runtime_observability 없음/);
  assert.match(html, /요청 ID: /);
  assert.match(html, /상관 ID: /);
  assert.match(html, /request_id=/);
  assert.match(html, /correlation_id=/);
  assert.match(html, /requested_stage=/);
  assert.match(html, /requested_module=/);
  assert.match(html, /대기 \/ 연결된 PTY 세션이 없어 즉시 전송할 수 없습니다\./);
  assert.match(html, /가능 \/ 현재 선택된 PTY 세션으로 즉시 전송할 수 있습니다\./);
  assert.match(html, /showToast\('stage 실행 추적값 복사 완료'\);/);
  assert.match(html, /showToast\('stage 실행 추적값 복사 실패'\);/);
  assert.match(html, /showToast\('stage 실행 추적값 실행 패널 반영 완료'\);/);
  assert.match(html, /showToast\('채울 stage 실행 추적값이 없습니다\.'\);/);
  assert.match(html, /sendPromptNow\(\);/);
  assert.match(html, /onclick="sendStageRunTracePrompt\(' \+ failureFocusEntry\.index \+ '\)"' \+ htmlDisabled\(traceSendDisabled\)/);
  assert.match(html, /onclick="sendStageRunTracePrompt\(' \+ entry\.index \+ '\)"' \+ htmlDisabled\(traceSendDisabled\)/);
  assert.match(html, /onclick="sendStageRunTracePrompt\(\)"' \+ htmlDisabled\(traceSendDisabled\)/);
  assert.match(html, /scrollIntoView\(\{ block: 'center', behavior: 'smooth' \}\)/);
  assert.match(html, /function matchesStageRunHistoryFilter\(report, filter\)/);
  assert.match(html, /function compareStageRunHistoryEntries\(left, right, sortMode\)/);
  assert.match(html, /function restoreStageRunHistorySelection\(report\)/);
  assert.match(html, /S\.execution\.selectedWorkerIndex = Math\.max\(0, Number\.parseInt\(workerEl\.value, 10\) \|\| 0\);/);
  assert.match(html, /S\.execution\.rollbackTargetDomain = String\(rollbackEl\.value \|\| ''\)\.trim\(\);/);
  assert.match(html, /S\.stageRun\.selectedStage = String\(stageEl\.value \|\| 'D'\)\.trim\(\)\.toUpperCase\(\);/);
  assert.match(html, /S\.stageRun\.selectedModule = String\(moduleEl\.value \|\| ''\)\.trim\(\);/);
  assert.match(html, /S\.execution\.currentWorkerIndex = Number\.isInteger\(execution\.current_worker_index\)/);
  assert.match(html, /S\.execution\.activeWorkerIndex = Number\.isInteger\(scheduler\.active_worker_index\)/);
  assert.match(html, /var runtimeWorkerIndex = Number\.isInteger\(S\.execution\.currentWorkerIndex\)/);
  assert.match(html, /S\.execution\.selectedWorkerIndex = runtimeWorkerIndex;/);
  assert.match(html, /\[' \+ String\(indexValue\) \+ '\] ' \+ name/);
  assert.match(html, /executionWorkerLabel\(selectedWorker, selectedWorkerIndex\)/);
  assert.match(html, /var label = executionWorkerLabel\(worker, index\);/);
  assert.match(html, /return executionSummaryWithIndexedWorker\(String\(brief\.currentExecution\)\.trim\(\), S\.execution\.currentActivity\);/);
  assert.match(html, /return executionSummaryWithIndexedWorker\(String\(brief\.lastDispatch\)\.trim\(\), dispatchActivity\);/);
  assert.match(html, /executionActivityWorkerLabel\(activity\) \|\| activity\.worker \|\| 'worker 없음'/);
  assert.match(html, /return indexedLabel \+ ' · ' \+ message;/);
  assert.match(html, /var previousWorkerIndex = S\.execution\.selectedWorkerIndex;/);
  assert.match(html, /var previousRollbackTarget = String\(S\.execution\.rollbackTargetDomain \|\| ''\)\.trim\(\);/);
  assert.match(html, /\|\| \(rollbackEl && previousRollbackTarget !== S\.execution\.rollbackTargetDomain\)/);
  assert.match(html, /refreshExecutionSelectionUi\(\);/);
  assert.match(html, /var errorText = executionFailureReasonSummary\(/);
  assert.match(html, /var failureLocation = executionFailureLocationSummary\(/);
  assert.match(html, /var message = executionNextActionBase\(\);/);
  assert.match(html, /return '실패 위치: ' \+ failureLocation \+ ' · ' \+ indexedMessage;/);
  assert.match(html, /var rollbackTarget = selectedRollbackDomain\(\);/);
  assert.match(html, /context\.push\('선택 worker: ' \+ executionWorkerLabel\(selectedWorker, selectedWorkerIndex\)\);/);
  assert.match(html, /context\.push\('롤백 대상: ' \+ String\(rollbackTarget\.label \|\| rollbackTarget\.id \|\| '없음'\)\);/);
  assert.match(html, /S\.execution\.statusDetail = context\.length > 0 \? context\.join\(' · '\) \+ ' · ' \+ nextAction : nextAction;/);
  assert.match(html, /return selectedWorker \? executionWorkerLabel\(selectedWorker, selectedWorkerIndex\) : '없음';/);
  assert.match(html, /'선택 도메인: ' \+ domainLabel/);
  assert.match(html, /'선택 worker: ' \+ selectedExecutionWorkerLabel\(\)/);
  assert.match(html, /parts\.push\('현재 실행: ' \+ currentExecution\);/);
  assert.match(html, /class="modal-warning-box"/);
  assert.match(html, /class="modal-context-list"/);
  assert.match(html, /class="modal-context-row"/);
  assert.match(html, /class="modal-warning-note"/);
  assert.match(html, /class="modal-validation-state"/);
  assert.match(html, /return '<div class="modal-warning-box">이 롤백은 즉시 적용되며 되돌리기 전까지 유지됩니다\.<\/div>'/);
  assert.match(html, /label: '선택 도메인', value: domainLabel/);
  assert.match(html, /label: '선택 worker', value: selectedExecutionWorkerLabel\(\)/);
  assert.match(html, /label: '현재 실행', value: executionCurrentSummary\(\) \|\| '없음'/);
  assert.match(html, /return \{ ok: false, message: '롤백 대상이 없어 확인할 수 없습니다\.' \};/);
  assert.match(html, /return \{ ok: false, message: '현재 화면에서 롤백 대상이 선택되지 않아 확인 버튼을 잠급니다\.' \};/);
  assert.match(html, /message: '현재 선택된 롤백 대상과 확인 대상이 달라 다시 선택 확인이 필요합니다\.',/);
  assert.match(html, /message: '현재 선택 컨텍스트가 확인되었습니다\. 롤백 사유를 검토한 뒤 확인을 진행하세요\.',/);
  assert.match(html, /if \(!modal \|\| modal\.style\.display === 'none'\) \{/);
  assert.match(html, /body\.innerHTML = rollbackModalMarkup\(modalTarget\);/);
  assert.match(html, /note\.className = 'modal-validation-state ' \+ \(state\.ok \? 'is-ready' : 'is-blocked'\);/);
  assert.match(html, /confirmButton\.disabled = !state\.ok;/);
  assert.match(html, /confirmButton\.setAttribute\('aria-disabled', state\.ok \? 'false' : 'true'\);/);
  assert.match(html, /var workerIndex = Number\.isInteger\(S\.execution\.selectedWorkerIndex\) \? S\.execution\.selectedWorkerIndex : 0;/);
  assert.match(html, /worker 선택 확인 필요/);
  assert.match(html, /function openExecutionRollbackModal\(\)/);
  assert.match(html, /selectNode\(rollbackTarget\.id\);/);
  assert.match(html, /S\.execution\.rollbackTargetDomain = selectedNode\.id;/);
  assert.match(html, /modal\.querySelector\('\.modal-body'\)\.innerHTML = rollbackModalMarkup\(n\);/);
  assert.match(html, /modal\.querySelector\('\.modal-reason'\)\.value = '';/);
  assert.match(html, /refreshRollbackModalContext\(\);/);
  assert.match(html, /refreshRollbackModalValidation\(\);/);
  assert.match(html, /var validation = rollbackModalValidationState\(\);/);
  assert.match(html, /setExecutionStatus\('warning', '롤백 확인 필요', validation\.message\);/);
  assert.match(html, /showToast\('롤백 대상 다시 확인 필요'\);/);
  assert.match(html, /window\.openExecutionRollbackModal = openExecutionRollbackModal;/);
  assert.match(html, /window\.runSelectedStage = runSelectedStage;/);
  assert.match(html, /window\.retryLastStageRun = retryLastStageRun;/);
  assert.match(html, /window\.reuseStageRunHistory = reuseStageRunHistory;/);
  assert.match(html, /window\.rerunStageHistory = rerunStageHistory;/);
  assert.match(html, /window\.focusStageRunFailureSignal = focusStageRunFailureSignal;/);
  assert.match(html, /window\.focusPinnedStageRunFailureSignal = focusPinnedStageRunFailureSignal;/);
  assert.match(html, /window\.stepStageRunFailureMatch = stepStageRunFailureMatch;/);
  assert.match(html, /window\.setStageRunHistoryFilter = setStageRunHistoryFilter;/);
  assert.match(html, /window\.setStageRunSignalHistoryView = setStageRunSignalHistoryView;/);
  assert.match(html, /window\.setStageRunSignalGroupCollapsed = setStageRunSignalGroupCollapsed;/);
  assert.match(html, /window\.setStageRunHistorySort = setStageRunHistorySort;/);
  assert.match(html, /window\.copyStageRunTraceQuery = copyStageRunTraceQuery;/);
  assert.match(html, /window\.loadStageRunTracePrompt = loadStageRunTracePrompt;/);
  assert.match(html, /window\.loadStageRunContractRecoveryPrompt = loadStageRunContractRecoveryPrompt;/);
  assert.match(html, /window\.sendStageRunContractRecoveryPrompt = sendStageRunContractRecoveryPrompt;/);
  assert.match(html, /window\.refreshStageRunContract = refreshStageRunContract;/);
  assert.match(html, /window\.sendStageRunTracePrompt = sendStageRunTracePrompt;/);
  assert.match(html, /function resolveControlCenterDeepLinkContext\(\)/);
  assert.match(html, /saveDeepLinkClientStorage\(DEEP_LINK_CONTEXT_STORAGE_KEY/);
  assert.match(html, /loadDeepLinkClientStorage\(DEEP_LINK_CONTEXT_STORAGE_KEY/);
  assert.match(html, /idempotencyPayload: \{ worker_index: workerIndex \}/);
  assert.match(html, /idempotencyScope: 'planning-stage-run:'/);
  assert.match(html, /body: JSON\.stringify\(\{ worker_index: workerIndex \}\)/);
  assert.match(html, /showToast\(workerName \+ ' 즉시 전송 완료'\);/);
});
